#!/bin/bash
# run_aiesim.sh — build the hand-written ps.so and run aiesimulator for one
# compiler arm of the Peano-vs-Chess A/B (see ../README-COMPILER-AB.md).
#
# The aiesim workdir is generated by aiecc --aiesim (see ../bench_compiler_ab.sh
# step "aiesim"; the arm dirs hold design.mlir, mm_32x64x128.o and the generated
# design.mlir.prj/). This script:
#   1. builds sim/ps/ps.so = genwrapper_for_ps.cpp + txn_replay_main.cpp
#      + test_library.cpp + libmemory_allocator_sim_aie.a
#   2. copies the arm's insts.txt next to the sim as insts.txt
#   3. runs aiesimulator --pkg-dir=<prj>/sim, prints the PASS/FAIL + C stats
#
# Needs: strixhalo (Vitis 2026.1 aietools + mlir-aie + license), g++.
# NOTE: aiesimulator is slow on the full 128x2048x8192 design (millions of
# cycles); start with WAIT_US small / a shrunk design to validate plumbing.
set -euo pipefail

AISIM_DIR="$(cd "$(dirname "$0")" && pwd)"
TESTS="$(dirname "$AISIM_DIR")"
REPO="$(cd "$AISIM_DIR/../../../.." && pwd)"
MLIR_AIE="${MLIR_AIE:-$HOME/mlir-aie}"
# 2025.2 is the WORKING aiesimulator for aie2p — 2026.1's aie2psimmsm
# segfaults at startup on any npu2 design (empty aiesol).
VITIS="${VITIS:-$HOME/Xilinx/2025.2}"
AIETOOLS="$VITIS/Vitis/aietools"
TL_INC="$MLIR_AIE/.venv/lib/python3.14/site-packages/mlir_aie/runtime_lib/x86_64/test_lib/include"
TL_LIB="$MLIR_AIE/.venv/lib/python3.14/site-packages/mlir_aie/runtime_lib/x86_64/test_lib/lib"
XAIE_INC="$MLIR_AIE/install/runtime_lib/x86_64/xaiengine/include"
XAIE_LIB="$MLIR_AIE/install/runtime_lib/x86_64/xaiengine/lib"
GENWRAP="$MLIR_AIE/install/aie_runtime_lib/AIE2P/aiesim/genwrapper_for_ps.cpp"

# workdir with the generated aiesim (*.mlir.prj/) — from bench_compiler_ab
PRJ_DIR="${1:?usage: run_aiesim.sh <arm-workdir> [WAIT_US] [insts-name]}"
WAIT_US="${2:-1000}"
INSTS="${3:-insts.txt}"
# locate the prj dir (design.mlir.prj for aiecc designs, <name>.mlir.prj for raw)
PRJ="$PRJ_DIR/design.mlir.prj"
[ -d "$PRJ" ] || PRJ=$(ls -d "$PRJ_DIR"/*.mlir.prj 2>/dev/null | head -1)
[ -n "$PRJ" ] && [ -d "$PRJ" ] || { echo "ERROR: no *.mlir.prj under $PRJ_DIR" >&2; exit 1; }

for p in "$GENWRAP" "$PRJ/aie_inc.cpp" "$AIETOOLS/bin/aiesimulator"; do
  [ -e "$p" ] || { echo "ERROR: missing $p" >&2; exit 1; }
done
[ -e "$PRJ_DIR/$INSTS" ] || { echo "ERROR: $PRJ_DIR/$INSTS not found" >&2; exit 1; }

export PATH="$AIETOOLS/bin:/opt/xilinx/xrt/bin:$PATH"
export XILINXD_LICENSE_FILE="$HOME/.Xilinx/Xilinx.lic"
export LD_LIBRARY_PATH="$XAIE_LIB:$AIETOOLS/lib/lnx64.o:$AIETOOLS/lib/lnx64.o/Ubuntu:$AIETOOLS/data/osci_systemc/lib/lnx64:${LD_LIBRARY_PATH:-}"

echo "== 1/3 build ps.so =="
mkdir -p "$PRJ/sim/ps"
g++ -O2 -shared -fPIC -fpermissive \
  -Wno-deprecated-declarations -Wno-format-security \
  -DSC_INCLUDE_DYNAMIC_PROCESSES -D__AIESIM__ -D__PS_INIT_AIE__ \
  -DAIE_OPTION_SCALAR_FLOAT_ON_VECTOR -D__AIEARCH__=21 \
  "-Dmain(...)=ps_main(...)" \
  "-DWAIT_US=$WAIT_US" \
  ${AISIM_DEFS:-} \
  -I "$PRJ" \
  -I "$AIETOOLS/include" \
  -I "$XAIE_INC" \
  -I "$AIETOOLS/data/osci_systemc/include" \
  -I "$AIETOOLS/include/xtlm/include" \
  -I "$AIETOOLS/include/common_cpp/common_cpp_v1_0/include" \
  -I "$TL_INC" \
  "$GENWRAP" "$TESTS/aiesim/txn_replay_main.cpp" \
  "$MLIR_AIE/runtime_lib/test_lib/test_library.cpp" \
  "$TL_LIB/libmemory_allocator_sim_aie.a" \
  -L "$XAIE_LIB" -lxaienginecdo \
  -L "$AIETOOLS/lib/lnx64.o" -L "$AIETOOLS/lib/lnx64.o/Ubuntu" \
  -L "$AIETOOLS/data/osci_systemc/lib/lnx64" \
  -Wl,--as-needed -lsystemc -lxtlm \
  -o "$PRJ/sim/ps/ps.so" 2>&1 | tail -15
echo "  OK: $PRJ/sim/ps/ps.so ($(stat -c%s "$PRJ/sim/ps/ps.so") B)"

echo "== 2/3 stage insts =="
cp "$PRJ_DIR/$INSTS" "$PRJ/insts.txt"
echo "  OK: $PRJ/insts.txt"

echo "== 3/3 run aiesimulator =="
cd "$PRJ"
aiesimulator --pkg-dir=sim --simulation-cycle-timeout=200000000 2>&1 | \
  grep -v -E "^\[INFO\]|^\[WARNING\]" | tail -40
echo "aiesimulator exit=$?"
