// test_moe_pack.c — verify the Round-50 MoE weight-BO packing (model.c)
// reproduces the byte-verified reference (tools/verify_moe_current_layout.py).
//
// Build:
//   gcc -O2 -std=c11 -I../include test_moe_pack.c ../src/model.c -o test_moe_pack -lm
// Run:
//   ./test_moe_pack [model.q4nx]     # dumps /tmp/pool_c.bin + /tmp/linear5_c.bin
//
// Compare (reference generated by verify_moe_current_layout.py's logic):
//   cmp /tmp/pool_c.bin /tmp/pool_ref.bin && echo POOL-OK
//   cmp /tmp/linear5_c.bin /tmp/linear5_ref.bin && echo LINEAR5-OK
#include "model.h"
#include "common.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char** argv) {
    const char* path = argc > 1 ? argv[1]
        : "/home/bcloud/.config/flm/models/Qwen3.6-35B-A3B-NPU2/model.q4nx";
    ModelConfig cfg = QWEN3_0_6B_CONFIG;
    ModelWeights* mw = model_load(path, cfg);
    if (!mw) { fprintf(stderr, "model_load failed\n"); return 1; }
    printf("layers=%d hidden=%d vocab=%d\n",
           mw->config.num_layers, mw->config.hidden_size, mw->config.vocab_size);

    // sanity: MoE tensors present on layer 0
    LayerWeights* l0 = &mw->layers[0];
    printf("L0 up_exps ndim=%d size=%llu  gate_exps ndim=%d  down_exps ndim=%d\n",
           l0->up_exps_weight.ndim, (unsigned long long)l0->up_exps_weight.data_size,
           l0->gate_exps_weight.ndim, l0->down_exps_weight.ndim);

    uint8_t* pool = (uint8_t*)malloc(512u * 1024u * 1024u);
    if (!pool) return 1;
    memset(pool, 0, 512u * 1024u * 1024u);
    int64_t n = npu_pack_moe_expert_pool(pool, mw, 0);
    printf("expert pool layer 0: %lld bytes\n", (long long)n);
    if (n != 478146560) { fprintf(stderr, "UNEXPECTED pool size\n"); return 1; }
    FILE* f = fopen("/tmp/pool_c.bin", "wb");
    fwrite(pool, 1, (size_t)n, f); fclose(f);

    uint8_t* b5 = (uint8_t*)malloc(5242880);
    int64_t n5 = npu_pack_moe_linear5_bo(b5, mw, 6);
    printf("linear5 layer 6: %lld bytes\n", (long long)n5);
    if (n5 != 5242880) { fprintf(stderr, "UNEXPECTED linear5 size\n"); return 1; }
    f = fopen("/tmp/linear5_c.bin", "wb");
    fwrite(b5, 1, (size_t)n5, f); fclose(f);

    free(pool); free(b5);
    model_free(mw);
    printf("wrote /tmp/pool_c.bin + /tmp/linear5_c.bin\n");
    return 0;
}
