// arch_mapping_selfcheck.cpp — self-check for the one-bin dispatch arch registry.
// Verifies rcpp_arch_from_string: new bring-up mappings + regression on existing ones.
//
// Run:
//   g++ -std=c++17 -Iinclude Testing/arch_mapping_selfcheck.cpp -o /tmp/arch_check && /tmp/arch_check
#include <cstdio>
#include <cstring>
#include "rocm_cpp/bitnet_model.h"

int main() {
    int total = 0, fails = 0;
    auto check = [&](const char* s, rcpp_arch_t expect, const char* label) {
        ++total;
        rcpp_arch_t got = rcpp_arch_from_string(s);
        if (got != expect) {
            std::printf("FAIL %-26s got=%d want=%d\n", label, (int)got, (int)expect);
            ++fails;
        }
    };

    // ── 2026-08-13 bring-up pilot: LLaMA-layout architectures (GGUF + HF class names)
    check("openelm", RCPP_ARCH_LLAMA, "openelm");
    check("OpenELMForCausalLM", RCPP_ARCH_LLAMA, "OpenELMForCausalLM");
    check("nemotron", RCPP_ARCH_NEMOTRON, "nemotron (Nemotron-3 dense)");
    check("NemotronForCausalLM", RCPP_ARCH_NEMOTRON, "NemotronForCausalLM");
    check("minicpm", RCPP_ARCH_LLAMA, "minicpm");
    check("MiniCPMForCausalLM", RCPP_ARCH_LLAMA, "MiniCPMForCausalLM");

    // ── Regression: existing mappings
    check("llama", RCPP_ARCH_LLAMA, "llama");
    check("starcoder2", RCPP_ARCH_LLAMA, "starcoder2");
    check("baichuan2", RCPP_ARCH_LLAMA, "baichuan2");
    check("BaichuanForCausalLM", RCPP_ARCH_LLAMA, "BaichuanForCausalLM");
    check("exaone", RCPP_ARCH_LLAMA, "exaone");
    check("ExaoneForCausalLM", RCPP_ARCH_LLAMA, "ExaoneForCausalLM");
    check("solar", RCPP_ARCH_LLAMA, "solar");
    check("internlm2", RCPP_ARCH_LLAMA, "internlm2");
    check("xverse", RCPP_ARCH_LLAMA, "xverse");
    check("qwen", RCPP_ARCH_QWEN2, "qwen (Qwen1)");
    check("qwen3", RCPP_ARCH_QWEN3, "qwen3");
    check("qwen2", RCPP_ARCH_QWEN2, "qwen2");
    check("gemma4", RCPP_ARCH_GEMMA, "gemma4");
    check("granite", RCPP_ARCH_GEMMA, "granite");
    check("phi4", RCPP_ARCH_PHI, "phi4");
    check("deepseek2", RCPP_ARCH_DEEPSEEK, "deepseek2");
    check("deepseek_v4", RCPP_ARCH_DEEPSEEK_V4, "deepseek_v4");
    check("zamba2", RCPP_ARCH_ZAMBA2, "zamba2");
    check("mamba", RCPP_ARCH_MAMBA, "mamba");
    check("falcon3", RCPP_ARCH_FALCON, "falcon3");
    check("rw", RCPP_ARCH_FALCON, "falcon via rw");
    check("tinyllama", RCPP_ARCH_LLAMA, "tinyllama");
    check("openlm", RCPP_ARCH_LLAMA, "openlm");
    check("stablelmepoch", RCPP_ARCH_LLAMA, "stablelmepoch");
    check("mobilellm", RCPP_ARCH_LLAMA, "mobilellm");
    check("customllama", RCPP_ARCH_LLAMA, "customllama");
    check("ministral", RCPP_ARCH_MISTRAL, "ministral");
    check("olmo3", RCPP_ARCH_OLMO, "olmo3");
    check("gpt2lmheadcustom", RCPP_ARCH_GPT2, "gpt2 custom");
    check("yi", RCPP_ARCH_LLAMA, "yi");
    check("glm4", RCPP_ARCH_LLAMA, "glm4");
    check("decilm", RCPP_ARCH_LLAMA, "decilm");
    check("hunyuan", RCPP_ARCH_LLAMA, "hunyuan");
    check("nanbeige", RCPP_ARCH_LLAMA, "nanbeige");
    check("biogpt", RCPP_ARCH_GPT2, "biogpt");
    check("xglm", RCPP_ARCH_GPT2, "xglm");
    check("mixformersequential", RCPP_ARCH_PHI, "phi-1.5");
    check("kimi", RCPP_ARCH_KIMI_K3, "kimi");
    check("qwen35moe", RCPP_ARCH_QWEN35, "qwen35moe");
    check("whisper", RCPP_ARCH_WHISPER, "whisper");

    // ── MONSTER breadth batch 2026-08-14 (llama.cpp conversion/ registry) ──
    check("smollm3", RCPP_ARCH_LLAMA, "smollm3 (SmolLM3ForCausalLM)");
    check("apertus", RCPP_ARCH_LLAMA, "apertus (ApertusForCausalLM)");
    check("cohere", RCPP_ARCH_LLAMA, "cohere (CohereForCausalLM)");
    check("gptbigcode", RCPP_ARCH_LLAMA, "gptbigcode (GPTBigCodeForCausalLM)");
    check("internlm3", RCPP_ARCH_LLAMA, "internlm3 (InternLM3ForCausalLM)");
    check("mixtral", RCPP_ARCH_MISTRAL, "mixtral (MixtralForCausalLM)");
    check("qwen2moe", RCPP_ARCH_QWEN2, "qwen2moe (Qwen2MoeForCausalLM)");
    check("qwen3moe", RCPP_ARCH_QWEN3, "qwen3moe (Qwen3MoeForCausalLM)");
    check("deepseekv2", RCPP_ARCH_DEEPSEEK, "deepseekv2 (DeepseekV2ForCausalLM)");
    check("deepseekv3", RCPP_ARCH_DEEPSEEK, "deepseekv3 (DeepseekV3ForCausalLM)");
    check("deepseekv4", RCPP_ARCH_DEEPSEEK_V4, "deepseekv4 (DeepseekV4ForCausalLM)");
    check("gpt2", RCPP_ARCH_GPT2, "gpt2 (GPT2LMHeadModel)");
    check("gptneox", RCPP_ARCH_GPTNEOX, "gptneox (GPTNeoXForCausalLM)");
    check("opt", RCPP_ARCH_OPT, "opt (OPTForCausalLM)");
    check("gptneo", RCPP_ARCH_GPTNEO, "gptneo (GPTNeoForCausalLM)");
    check("codegen", RCPP_ARCH_CODEGEN, "codegen (CodeGenForCausalLM)");
    check("gptj", RCPP_ARCH_GPTJ, "gptj (GPTJForCausalLM)");
    check("gptoss", RCPP_ARCH_GPTOSS, "gptoss (GptOssForCausalLM)");
    check("step1", RCPP_ARCH_STEP1, "step1 (Step1ForCausalLM)");
    check("step1moe", RCPP_ARCH_STEP1, "step1moe (Step1MoEForCausalLM — dense weights in practice)");
    check("bloom", RCPP_ARCH_BLOOM, "bloom (BloomForCausalLM — fused qkv, linear ALiBi)");

    // ── Decision (pilot #10): unknown archs -> UNKNOWN (loud), not BITNET
    check("totally_unknown_arch", RCPP_ARCH_UNKNOWN, "unknown->UNKNOWN (loud fail)");

    // ── VLM conditional-generation classes (MAX-style text-decoder mapping) ──
    // The reader strips "forconditionalgeneration"/"forvisiontext2text" suffixes
    // (see safetensors_reader.cpp) before calling rcpp_arch_from_string, so these
    // assert the stripped forms the mapping actually receives.
    check("qwen3_5", RCPP_ARCH_QWEN35, "qwen3_5 (Qwen3.5 dense)");
    check("qwen3_5moe", RCPP_ARCH_QWEN35, "qwen3_5moe (Qwen3.5-MoE)");
    check("mistral3", RCPP_ARCH_MISTRAL, "mistral3 (Mistral3-VL text decoder)");
    check("qwen2_5_vl", RCPP_ARCH_QWEN2VL, "qwen2_5_vl (Qwen2.5-VL text decoder)");
    check("qwen3vlmoe", RCPP_ARCH_QWEN3VL, "qwen3vlmoe (Qwen3-VL-MoE)");
    check("gemma4unified", RCPP_ARCH_GEMMA, "gemma4unified (Gemma4-Unified)");
    check("qwen3_5vl", RCPP_ARCH_QWEN35, "qwen3_5vl (Qwen3.5-VL text decoder)");
    // Reader-strip equivalence (suffix -> stripped form -> token)
    check("gemma3", RCPP_ARCH_GEMMA, "gemma3 (from Gemma3ForConditionalGeneration)");
    check("gemma4", RCPP_ARCH_GEMMA, "gemma4 (from Gemma4ForConditionalGeneration)");
    check("qwen2vl", RCPP_ARCH_QWEN2VL, "qwen2vl (from Qwen2VLForConditionalGeneration)");
    check("qwen3vl", RCPP_ARCH_QWEN3VL, "qwen3vl (from Qwen3VLForConditionalGeneration)");
    check("llava", RCPP_ARCH_QWEN2VL, "llava (from LlavaForConditionalGeneration)");
    check("smolvlm", RCPP_ARCH_QWEN2VL, "smolvlm (from SmolVLMForConditionalGeneration)");
    check("paligemma", RCPP_ARCH_GEMMA, "paligemma (from PaliGemmaForConditionalGeneration)");
    // Encoder-decoder stays UNKNOWN (decoder-only engine, out of scope)
    check("t5", RCPP_ARCH_UNKNOWN, "t5 enc-dec stays UNKNOWN");
    check("mt5", RCPP_ARCH_UNKNOWN, "mt5 enc-dec stays UNKNOWN");
    check("bart", RCPP_ARCH_UNKNOWN, "bart enc-dec stays UNKNOWN");

    // ── HF model_type values (reader falls back to model_type when the
    //    class name maps UNKNOWN — extraction 2026-08-15) ──
    check("gpt_neox", RCPP_ARCH_GPTNEOX, "model_type gpt_neox");
    check("gpt_neo", RCPP_ARCH_GPTNEO, "model_type gpt_neo");
    check("gpt_bigcode", RCPP_ARCH_LLAMA, "model_type gpt_bigcode");
    check("qwen2_vl", RCPP_ARCH_QWEN2VL, "model_type qwen2_vl");
    check("qwen3_vl", RCPP_ARCH_QWEN3VL, "model_type qwen3_vl");
    check("qwen3_moe", RCPP_ARCH_QWEN3, "model_type qwen3_moe");
    check("qwen2_moe", RCPP_ARCH_QWEN2, "model_type qwen2_moe");
    check("granite_moe", RCPP_ARCH_GEMMA, "model_type granite_moe");
    check("gemma3_text", RCPP_ARCH_GEMMA, "model_type gemma3_text");
    check("llava", RCPP_ARCH_QWEN2VL, "model_type llava");
    check("llava_llama", RCPP_ARCH_LLAMA, "model_type llava_llama");
    check("llava_qwen2", RCPP_ARCH_QWEN2, "model_type llava_qwen2");
    check("deepseek_v2", RCPP_ARCH_DEEPSEEK, "model_type deepseek_v2");
    check("deepseek_v3", RCPP_ARCH_DEEPSEEK, "model_type deepseek_v3");
    check("cambrian_qwen", RCPP_ARCH_QWEN2, "model_type cambrian_qwen");
    check("hunyuan_v1_dense", RCPP_ARCH_LLAMA, "model_type hunyuan_v1_dense");
    check("seedoss", RCPP_ARCH_LLAMA, "model_type seedoss");
    check("glm4", RCPP_ARCH_LLAMA, "model_type glm4");
    check("glm4moe", RCPP_ARCH_LLAMA, "glm4moe (GLM-4-MoE)");
    check("glmmoedsa", RCPP_ARCH_LLAMA, "glmmoedsa (GLM-4.5 MoE)");
    check("glm4moelite", RCPP_ARCH_LLAMA, "glm4moelite (GLM-4-MoE-Lite)");
    check("nemotronh", RCPP_ARCH_NEMOTRONH, "nemotronh (Nemotron-H)");
    check("nemotron_h", RCPP_ARCH_NEMOTRONH, "model_type nemotron_h");
    check("fp8_qwen3", RCPP_ARCH_QWEN3, "model_type fp8_qwen3 (FP8 wrapper)");
    check("fp8_llama", RCPP_ARCH_LLAMA, "model_type fp8_llama");
    check("bit_llama", RCPP_ARCH_LLAMA, "model_type bit_llama");

    // ── census tail sweep checks ──
    check("adavocabgemma", RCPP_ARCH_GEMMA, "adavocabgemma");
    check("aicraftar-tharo.g-conditionalgeneration", RCPP_ARCH_QWEN2VL, "aicraftar-tharo.g-conditionalgeneration");
    check("antihal", RCPP_ARCH_GEMMA, "antihal");
    check("asvdopt", RCPP_ARCH_OPT, "asvdopt");
    check("automodel", RCPP_ARCH_MISTRAL, "automodel");
    check("backpackgpt2", RCPP_ARCH_GPT2, "backpackgpt2");
    check("bunnyqwen", RCPP_ARCH_QWEN2, "bunnyqwen");
    check("careaqa", RCPP_ARCH_LLAMA, "careaqa");
    check("chexagent", RCPP_ARCH_PHI, "chexagent");
    check("codebharat", RCPP_ARCH_LLAMA, "codebharat");
    check("cogpt2", RCPP_ARCH_GPT2, "cogpt2");
    check("custom_mpt", RCPP_ARCH_LLAMA, "custom_mpt");
    check("custombiogpt", RCPP_ARCH_GPT2, "custombiogpt");
    check("custommixtral", RCPP_ARCH_MISTRAL, "custommixtral");
    check("custommodel3", RCPP_ARCH_GPTNEOX, "custommodel3");
    check("dashqphi3", RCPP_ARCH_PHI, "dashqphi3");
    check("deepseekv2mobe", RCPP_ARCH_DEEPSEEK, "deepseekv2mobe");
    check("deepseekv2sparsemobe", RCPP_ARCH_DEEPSEEK, "deepseekv2sparsemobe");
    check("deepseekv3forcausallmnextn", RCPP_ARCH_DEEPSEEK, "deepseekv3forcausallmnextn");
    check("denseformer", RCPP_ARCH_LLAMA, "denseformer");
    check("dflashlaguna", RCPP_ARCH_LAGUNA, "dflashlaguna");
    check("dribble", RCPP_ARCH_PHI, "dribble");
    check("dribblellama", RCPP_ARCH_LLAMA, "dribblellama");
    check("duolaguna", RCPP_ARCH_LAGUNA, "duolaguna");
    check("dusmistral", RCPP_ARCH_MISTRAL, "dusmistral");
    check("edullm", RCPP_ARCH_MISTRAL, "edullm");
    check("efficientdlm", RCPP_ARCH_QWEN3, "efficientdlm");
    check("exaonetd", RCPP_ARCH_LLAMA, "exaonetd");
    check("flashgptneox", RCPP_ARCH_GPTNEOX, "flashgptneox");
    check("flaxgptj", RCPP_ARCH_GPTJ, "flaxgptj");
    check("forcausallm", RCPP_ARCH_GEMMA, "forcausallm");
    check("fsdpgptoss", RCPP_ARCH_GPTOSS, "fsdpgptoss");
    check("gemmagain", RCPP_ARCH_GEMMA, "gemmagain");
    check("gfusionfordiffusionlm", RCPP_ARCH_DEEPSEEK, "gfusionfordiffusionlm");
    check("gistgptneo", RCPP_ARCH_GPTNEO, "gistgptneo");
    check("glamm", RCPP_ARCH_QWEN2VL, "glamm");
    check("glus", RCPP_ARCH_QWEN2VL, "glus");
    check("gpt2forquestionanswering", RCPP_ARCH_GPT2, "gpt2forquestionanswering");
    check("gpt2forsequenceclassification", RCPP_ARCH_GPT2, "gpt2forsequenceclassification");
    check("gpt2lmandvaluehead", RCPP_ARCH_GPT2, "gpt2lmandvaluehead");
    check("gptbigcodeforsequenceclassification", RCPP_ARCH_LLAMA, "gptbigcodeforsequenceclassification");
    check("gretriever", RCPP_ARCH_LLAMA, "gretriever");
    check("int8opt", RCPP_ARCH_OPT, "int8opt");
    check("internlm2forreward", RCPP_ARCH_LLAMA, "internlm2forreward");
    check("internlmxcomposer2", RCPP_ARCH_LLAMA, "internlmxcomposer2");
    check("interns2preview", RCPP_ARCH_QWEN35, "interns2preview");
    check("kblamphi3", RCPP_ARCH_PHI, "kblamphi3");
    check("layerwiseminicpm", RCPP_ARCH_LLAMA, "layerwiseminicpm");
    check("leanllama", RCPP_ARCH_LLAMA, "leanllama");
    check("leanmixtral", RCPP_ARCH_MISTRAL, "leanmixtral");
    check("lexadelta", RCPP_ARCH_GPTOSS, "lexadelta");
    check("lfm2bidirectionalformaskedlm", RCPP_ARCH_LFM2, "lfm2bidirectionalformaskedlm");
    check("lightonocr", RCPP_ARCH_MISTRAL, "lightonocr");
    check("llamaforcausallmeagle3", RCPP_ARCH_LLAMA, "llamaforcausallmeagle3");
    check("llamaforsequenceclassification", RCPP_ARCH_LLAMA, "llamaforsequenceclassification");
    check("llavaqwen", RCPP_ARCH_QWEN2VL, "llavaqwen");
    check("loragpt2", RCPP_ARCH_GPT2, "loragpt2");
    check("mahler60/prueba", RCPP_ARCH_GPTNEOX, "mahler60/prueba");
    check("mamba2", RCPP_ARCH_MAMBA, "mamba2");
    check("mambamodel", RCPP_ARCH_MAMBA, "mambamodel");
    check("memllama", RCPP_ARCH_LLAMA, "memllama");
    check("meteormamba", RCPP_ARCH_MAMBA, "meteormamba");
    check("mimoaudio", RCPP_ARCH_QWEN2, "mimoaudio");
    check("miniphi3", RCPP_ARCH_PHI, "miniphi3");
    check("mixformervlsequential", RCPP_ARCH_PHI, "mixformervlsequential");
    check("mobillama", RCPP_ARCH_LLAMA, "mobillama");
    check("monoformer", RCPP_ARCH_LLAMA, "monoformer");
    check("moyi", RCPP_ARCH_QWEN2, "moyi");
    check("multiheadgptneo", RCPP_ARCH_GPTNEO, "multiheadgptneo");
    check("multimodalstarcoder2", RCPP_ARCH_LLAMA, "multimodalstarcoder2");
    check("mutorgemma", RCPP_ARCH_GEMMA, "mutorgemma");
    check("mybaichuan", RCPP_ARCH_LLAMA, "mybaichuan");
    check("myqwen", RCPP_ARCH_QWEN2, "myqwen");
    check("myxverse", RCPP_ARCH_LLAMA, "myxverse");
    check("notagen", RCPP_ARCH_GPT2, "notagen");
    check("olmo2forsequenceclassification", RCPP_ARCH_OLMO, "olmo2forsequenceclassification");
    check("olmo3sink", RCPP_ARCH_OLMO, "olmo3sink");
    check("olmomodel", RCPP_ARCH_OLMO, "olmomodel");
    check("opt_prompttuned_for_sentimentanalysis", RCPP_ARCH_OPT, "opt_prompttuned_for_sentimentanalysis");
    check("pawqwen3", RCPP_ARCH_QWEN3, "pawqwen3");
    check("phi3forsequenceclassification", RCPP_ARCH_PHI, "phi3forsequenceclassification");
    check("poptorchpipelinedgpt2", RCPP_ARCH_GPT2, "poptorchpipelinedgpt2");
    check("poptorchpipelinedwhisper", RCPP_ARCH_WHISPER, "poptorchpipelinedwhisper");
    check("qwen2forcausallmpostblocksteeringfixed", RCPP_ARCH_QWEN2, "qwen2forcausallmpostblocksteeringfixed");
    check("qwen2forprocessreward", RCPP_ARCH_QWEN2, "qwen2forprocessreward");
    check("qwen2forsequenceclassification", RCPP_ARCH_QWEN2, "qwen2forsequenceclassification");
    check("qwen2reasoning", RCPP_ARCH_QWEN2, "qwen2reasoning");
    check("qwen2vlaudio", RCPP_ARCH_QWEN2VL, "qwen2vlaudio");
    check("qwen2vlextended", RCPP_ARCH_QWEN2VL, "qwen2vlextended");
    check("qwen2vlforconditionalgenerationwithaudio", RCPP_ARCH_QWEN2VL, "qwen2vlforconditionalgenerationwithaudio");
    check("qwen3_5dllm", RCPP_ARCH_QWEN35, "qwen3_5dllm");
    check("qwen3forsequenceclassification", RCPP_ARCH_QWEN3, "qwen3forsequenceclassification");
    check("qwen3gated", RCPP_ARCH_QWEN3, "qwen3gated");
    check("qwen3mobe", RCPP_ARCH_QWEN3, "qwen3mobe");
    check("qwen3sparsemobe", RCPP_ARCH_QWEN3, "qwen3sparsemobe");
    check("qwen3vlseg", RCPP_ARCH_QWEN3VL, "qwen3vlseg");
    check("ruqwen2", RCPP_ARCH_QWEN2, "ruqwen2");
    check("serayuki", RCPP_ARCH_LLAMA, "serayuki");
    check("sewy3", RCPP_ARCH_GEMMA, "sewy3");
    check("smollm3model", RCPP_ARCH_LLAMA, "smollm3model");
    check("stablediffcoder", RCPP_ARCH_LLAMA, "stablediffcoder");
    check("streamvln", RCPP_ARCH_QWEN2VL, "streamvln");
    check("symbolicgpt", RCPP_ARCH_GPT2, "symbolicgpt");
    check("titansmactransformer", RCPP_ARCH_LLAMA, "titansmactransformer");
    check("trimkvphi3", RCPP_ARCH_PHI, "trimkvphi3");
    check("trimkvqwen3", RCPP_ARCH_QWEN3, "trimkvqwen3");
    check("vlclipgptneox", RCPP_ARCH_GPTNEOX, "vlclipgptneox");
    check("whaleye", RCPP_ARCH_DEEPSEEK, "whaleye");
    check("xcuros", RCPP_ARCH_QWEN2, "xcuros");
    if (fails) {
        std::printf("ARCH MAPPING: %d/%d FAILED\n", fails, total);
        return 1;
    }


    // ── 2026-08-15 census pass-3 checks (new families + verified aliases) ──
    check("acip", RCPP_ARCH_ACIP, "acip");
    check("argonne", RCPP_ARCH_ARGONNE, "argonne");
    check("bailingmoe", RCPP_ARCH_LLAMA, "bailingmoe");
    check("bailingmoelinearv2", RCPP_ARCH_LLAMA, "bailingmoelinearv2");
    check("bailingmoev2", RCPP_ARCH_LLAMA, "bailingmoev2");
    check("bailingmoev2_5", RCPP_ARCH_LLAMA, "bailingmoev2_5");
    check("bailingmoev3", RCPP_ARCH_LLAMA, "bailingmoev3");
    check("bamba", RCPP_ARCH_LLAMA, "bamba");
    check("btlm", RCPP_ARCH_BTLM, "btlm");
    check("bvv", RCPP_ARCH_BVV, "bvv");
    check("ceno", RCPP_ARCH_CENO, "ceno");
    check("chatglm", RCPP_ARCH_CHATGLM, "chatglm");
    check("cognicapoe", RCPP_ARCH_COGNICAPOE, "cognicapoe");
    check("cubelm", RCPP_ARCH_CUBELM, "cubelm");
    check("daisy", RCPP_ARCH_DAISY, "daisy");
    check("duchifatcore", RCPP_ARCH_DUCHIFAT, "duchifatcore");
    check("duo", RCPP_ARCH_DUO, "duo");
    check("dynamicforgetting", RCPP_ARCH_DYNAMICFORGETTING, "dynamicforgetting");
    check("dynamicslidingwindow", RCPP_ARCH_DYNAMICSLIDINGWINDOW, "dynamicslidingwindow");
    check("emo", RCPP_ARCH_EMO, "emo");
    check("eshmun", RCPP_ARCH_ESHMUN, "eshmun");
    check("fimmy", RCPP_ARCH_FIMMY, "fimmy");
    check("financedecoder", RCPP_ARCH_FINANCEDECODER, "financedecoder");
    check("forgettingtransformer", RCPP_ARCH_FORGETTINGTRANSFORMER, "forgettingtransformer");
    check("gla", RCPP_ARCH_GLA, "gla");
    check("gpt2moe", RCPP_ARCH_GPT2, "gpt2moe");
    check("gptbert", RCPP_ARCH_GPTBERT, "gptbert");
    check("gptjxmoe", RCPP_ARCH_GPTJXMOE, "gptjxmoe");
    check("gptpangu", RCPP_ARCH_GPTPANGU, "gptpangu");
    check("grugmoe", RCPP_ARCH_GRUGMOE, "grugmoe");
    check("hgrn", RCPP_ARCH_HGRN, "hgrn");
    check("hybridqwen3", RCPP_ARCH_LLAMA, "hybridqwen3");
    check("hyenadna", RCPP_ARCH_HYENADNA, "hyenadna");
    check("instella", RCPP_ARCH_DEEPSEEK, "instella");
    check("jais", RCPP_ARCH_JAIS, "jais");
    check("keuralmoecausallm", RCPP_ARCH_KEURALMOE, "keuralmoecausallm");
    check("kimik25", RCPP_ARCH_DEEPSEEK, "kimik25");
    check("kormo", RCPP_ARCH_KORMO, "kormo");
    check("lightningtransformermodel", RCPP_ARCH_LIGHTNINGTRANSFORMER, "lightningtransformermodel");
    check("llada2moemodellm", RCPP_ARCH_LLADA2, "llada2moemodellm");
    check("llama4", RCPP_ARCH_LLAMA4, "llama4");
    check("llamamoe", RCPP_ARCH_LLAMAMOE, "llamamoe");
    check("longcatflash", RCPP_ARCH_LONGCAT, "longcatflash");
    check("looplm", RCPP_ARCH_LOOPLM, "looplm");
    check("modeling_sparsetral.mistral", RCPP_ARCH_MISTRAL, "modeling_sparsetral.mistral");
    check("modernbertdecoder", RCPP_ARCH_MODERNBERTDECODER, "modernbertdecoder");
    check("motif", RCPP_ARCH_MOTIF, "motif");
    check("multiscale", RCPP_ARCH_MULTISCALE, "multiscale");
    check("orkhon", RCPP_ARCH_ORKHON, "orkhon");
    check("polyverse", RCPP_ARCH_POLYVERSE, "polyverse");
    check("quasar", RCPP_ARCH_QUASAR, "quasar");
    check("raven", RCPP_ARCH_RAVEN, "raven");
    check("recurrentgemma", RCPP_ARCH_RECURRENTGEMMA, "recurrentgemma");
    check("reformermodelwithlmhead", RCPP_ARCH_REFORMER, "reformermodelwithlmhead");
    check("retnet", RCPP_ARCH_RETNET, "retnet");
    check("roformer", RCPP_ARCH_ROFORMER, "roformer");
    check("rwkv7", RCPP_ARCH_RWKV7, "rwkv7");
    check("sarvammla", RCPP_ARCH_SARVAM, "sarvammla");
    check("sarvammoe", RCPP_ARCH_SARVAM, "sarvammoe");
    check("skipmiddle", RCPP_ARCH_SKIPMIDDLE, "skipmiddle");
    check("spikewhalelm", RCPP_ARCH_SPIKEWHALE, "spikewhalelm");
    check("step3p5", RCPP_ARCH_STEP3P5, "step3p5");
    check("stl", RCPP_ARCH_STL, "stl");
    check("stripedhyenamodel", RCPP_ARCH_STRIPEDHYENA, "stripedhyenamodel");
    check("talkie", RCPP_ARCH_TALKIE, "talkie");
    check("telechat", RCPP_ARCH_TELECHAT, "telechat");
    check("transfoxl", RCPP_ARCH_TRANSFOXL, "transfoxl");
    check("transnormer", RCPP_ARCH_TRANSNORMER, "transnormer");
    check("twiny", RCPP_ARCH_TWINY, "twiny");
    check("xpertgpt", RCPP_ARCH_XPERTGPT, "xpertgpt");
    check("yatgpt", RCPP_ARCH_YATGPT, "yatgpt");


    // ── 2026-08-15 census pass-3 batch 2 checks ──
    check("adaptermoellavaqwen3", RCPP_ARCH_QWEN3VL, "adaptermoellavaqwen3");
    check("bananamind2pico", RCPP_ARCH_PICO, "bananamind2pico");
    check("bunnyphi", RCPP_ARCH_PHI, "bunnyphi");
    check("bunnyphi3", RCPP_ARCH_PHI, "bunnyphi3");
    check("colmaskmoellavaqwen3", RCPP_ARCH_QWEN3VL, "colmaskmoellavaqwen3");
    check("deepqwenvl", RCPP_ARCH_QWEN2VL, "deepqwenvl");
    check("dyncolmaskmoellavaqwen2", RCPP_ARCH_QWEN2VL, "dyncolmaskmoellavaqwen2");
    check("emu3", RCPP_ARCH_LLAMA, "emu3");
    check("gemma4unifiedassistant", RCPP_ARCH_GEMMA, "gemma4unifiedassistant");
    check("gptjx", RCPP_ARCH_GPTJ, "gptjx");
    check("graniteswitch", RCPP_ARCH_GEMMA, "graniteswitch");
    check("hgrn2", RCPP_ARCH_HGRN, "hgrn2");
    check("jais2", RCPP_ARCH_JAIS, "jais2");
    check("japanesestablelmalpha", RCPP_ARCH_LLAMA, "japanesestablelmalpha");
    check("llavagemma", RCPP_ARCH_GEMMA, "llavagemma");
    check("llavagpt2", RCPP_ARCH_GPT2, "llavagpt2");
    check("llavamamba", RCPP_ARCH_MAMBA, "llavamamba");
    check("llavampt", RCPP_ARCH_LLAMA, "llavampt");
    check("llavaqwen3", RCPP_ARCH_QWEN3VL, "llavaqwen3");
    check("maskmoellavaqwen3", RCPP_ARCH_QWEN3VL, "maskmoellavaqwen3");
    check("minimaxm1", RCPP_ARCH_MINIMAX, "minimaxm1");
    check("minimaxm3sparse", RCPP_ARCH_MINIMAX, "minimaxm3sparse");
    check("mobilintexaone", RCPP_ARCH_LLAMA, "mobilintexaone");
    check("moellavaqwen3", RCPP_ARCH_QWEN3VL, "moellavaqwen3");
    check("mosaicgpt", RCPP_ARCH_LLAMA, "mosaicgpt");
    check("nanogpt", RCPP_ARCH_GPT2, "nanogpt");
    check("nmmaskmoellavaqwen3", RCPP_ARCH_QWEN3VL, "nmmaskmoellavaqwen3");
    check("phi4flash", RCPP_ARCH_PHI, "phi4flash");
    check("plamo2", RCPP_ARCH_LLAMA, "plamo2");
    check("plamo3", RCPP_ARCH_LLAMA, "plamo3");
    check("qwen2chunking", RCPP_ARCH_QWEN2, "qwen2chunking");
    check("qwen3omnimoe", RCPP_ARCH_QWEN3VL, "qwen3omnimoe");
    check("rwkv6qwen2", RCPP_ARCH_QWEN2, "rwkv6qwen2");
    check("spatiallmqwen", RCPP_ARCH_QWEN2VL, "spatiallmqwen");
    check("stablelmalpha", RCPP_ARCH_LLAMA, "stablelmalpha");
    check("tpugemma3", RCPP_ARCH_GEMMA, "tpugemma3");


    // ── 2026-08-15 census pass-3 batch 3 checks ──
    check("activationsgptneo", RCPP_ARCH_GPTNEOX, "activationsgptneo");
    check("alibi", RCPP_ARCH_GPT2, "alibi");
    check("attnqwen", RCPP_ARCH_QWEN3, "attnqwen");
    check("bitmamba2lm", RCPP_ARCH_MAMBA, "bitmamba2lm");
    check("deltanet", RCPP_ARCH_QWEN3NEXT, "deltanet");
    check("extendedmpt", RCPP_ARCH_LLAMA, "extendedmpt");
    check("gemma3moe", RCPP_ARCH_GEMMA, "gemma3moe");
    check("gemmoe", RCPP_ARCH_GEMMA, "gemmoe");
    check("gptx2", RCPP_ARCH_LLAMA, "gptx2");
    check("gsa", RCPP_ARCH_LLAMA, "gsa");
    check("hybridgpt2", RCPP_ARCH_GPT2, "hybridgpt2");
    check("inflm", RCPP_ARCH_LLAMA, "inflm");
    check("latentmoellavaphi", RCPP_ARCH_PHI, "latentmoellavaphi");
    check("mfuyu", RCPP_ARCH_FUYU, "mfuyu");
    check("mixtralmole", RCPP_ARCH_MISTRAL, "mixtralmole");
    check("mosmamba", RCPP_ARCH_MAMBA, "mosmamba");
    check("museglimmer", RCPP_ARCH_MUSE, "museglimmer");
    check("nanochatgpt", RCPP_ARCH_NANOCHAT, "nanochatgpt");
    check("nmmaskmoellavaphi", RCPP_ARCH_PHI, "nmmaskmoellavaphi");
    check("pharia", RCPP_ARCH_LLAMA, "pharia");
    check("phi2moe", RCPP_ARCH_PHI, "phi2moe");
    check("qwen3sharedmoe", RCPP_ARCH_QWEN3, "qwen3sharedmoe");
    check("replitlm", RCPP_ARCH_LLAMA, "replitlm");
    check("step3p7", RCPP_ARCH_STEP3P5, "step3p7");
    check("tinygdn", RCPP_ARCH_QWEN3NEXT, "tinygdn");


    // ── 2026-08-15 census pass-3 batch 4 checks ──
    check("brujula", RCPP_ARCH_GPT2, "brujula");
    check("chesstrm", RCPP_ARCH_GPT2, "chesstrm");
    check("norovoxalphamoe", RCPP_ARCH_LLAMA, "norovoxalphamoe");
    check("phonelm", RCPP_ARCH_LLAMA, "phonelm");
    check("pinyincode", RCPP_ARCH_GPT2, "pinyincode");
    check("pit", RCPP_ARCH_GPT2, "pit");
    check("randygpt", RCPP_ARCH_GPT2, "randygpt");
    check("stickbreaking", RCPP_ARCH_GPT2, "stickbreaking");


    // ── 2026-08-15 census pass-3 batch 5 checks ──
    check("evo2", RCPP_ARCH_STRIPEDHYENA, "evo2");
    check("progen2forpretraining", RCPP_ARCH_GPT2, "progen2forpretraining");


    // ── 2026-08-15 census pass-3 batch 5b checks ──
    check("eagle3speculator", RCPP_ARCH_LLAMA, "eagle3speculator");
    check("embformer", RCPP_ARCH_LLAMA, "embformer");
    check("starvector", RCPP_ARCH_LLAMA, "starvector");


    // ── 2026-08-16 census pass-4 checks (config-verified tail batch 1) ──
    check("agora", RCPP_ARCH_QWEN2, "agora");
    check("andrea", RCPP_ARCH_GPTNEOX, "andrea");
    check("aquilamoe", RCPP_ARCH_LLAMA, "aquilamoe");
    check("babylm", RCPP_ARCH_OPT, "babylm");
    check("chessllm", RCPP_ARCH_GPTNEOX, "chessllm");
    check("custom", RCPP_ARCH_QWEN3, "custom");
    check("custommodel", RCPP_ARCH_FALCON, "custommodel");
    check("dendro", RCPP_ARCH_GPTNEOX, "dendro");
    check("eryon", RCPP_ARCH_MISTRAL, "eryon");
    check("expandedjetmoe", RCPP_ARCH_LLAMA, "expandedjetmoe");
    check("finermoe", RCPP_ARCH_LLAMA, "finermoe");
    check("gitllama", RCPP_ARCH_LLAMA, "gitllama");
    check("grin-moe", RCPP_ARCH_LLAMA, "grin-moe");
    check("gtlm", RCPP_ARCH_MISTRAL, "gtlm");
    check("helion", RCPP_ARCH_MISTRAL, "helion");
    check("hixtral", RCPP_ARCH_PHI, "hixtral");
    check("husky", RCPP_ARCH_QWEN2, "husky");
    check("i3", RCPP_ARCH_LLAMA, "i3");
    check("iconn", RCPP_ARCH_MISTRAL, "iconn");
    check("idefics2", RCPP_ARCH_LLAMA, "idefics2");
    check("intellix", RCPP_ARCH_QWEN2, "intellix");
    check("ivme", RCPP_ARCH_LLAMA, "ivme");
    check("llama3", RCPP_ARCH_LLAMA, "llama3");
    check("llamavision", RCPP_ARCH_LLAMA, "llamavision");
    check("llamoe", RCPP_ARCH_LLAMA, "llamoe");
    check("logos", RCPP_ARCH_MISTRAL, "logos");
    check("mgmomni", RCPP_ARCH_LLAMA, "mgmomni");
    check("minicpmo", RCPP_ARCH_LLAMA, "minicpmo");
    check("minimaxtext01", RCPP_ARCH_LLAMA, "minimaxtext01");
    check("moedl", RCPP_ARCH_LLAMA, "moedl");
    check("moegpt", RCPP_ARCH_GPTNEOX, "moegpt");
    check("moellavaqwen", RCPP_ARCH_LLAMA, "moellavaqwen");
    check("moellavaqwen2", RCPP_ARCH_LLAMA, "moellavaqwen2");
    check("monkey", RCPP_ARCH_LLAMA, "monkey");
    check("nanonano", RCPP_ARCH_QWEN3, "nanonano");
    check("new", RCPP_ARCH_QWEN3, "new");
    check("openaimoe", RCPP_ARCH_MISTRAL, "openaimoe");
    check("pangupromoe", RCPP_ARCH_LLAMA, "pangupromoe");
    check("phogpt", RCPP_ARCH_LLAMA, "phogpt");
    check("rabbit", RCPP_ARCH_LLAMA, "rabbit");
    check("ressai", RCPP_ARCH_GEMMA, "ressai");
    check("rwkv-6", RCPP_ARCH_RWKV, "rwkv-6");
    check("scidfm", RCPP_ARCH_LLAMA, "scidfm");
    check("tanuki", RCPP_ARCH_LLAMA, "tanuki");
    check("thanatos", RCPP_ARCH_GPTNEOX, "thanatos");
    check("tinymixtral", RCPP_ARCH_MISTRAL, "tinymixtral");
    check("traxlmistral", RCPP_ARCH_MISTRAL, "traxlmistral");
    check("trm", RCPP_ARCH_BLOOM, "trm");
    check("wikimini", RCPP_ARCH_GEMMA, "wikimini");
    check("yayi", RCPP_ARCH_BLOOM, "yayi");


    // ── 2026-08-16 census pass-4 checks (tail aliases + families) ──
    check("a2dgptneox", RCPP_ARCH_GPTNEOX, "a2dgptneox");
    check("arabicgpt", RCPP_ARCH_GPT2, "arabicgpt");
    check("axion", RCPP_ARCH_DEEPSEEK, "axion");
    check("batgpt", RCPP_ARCH_GPT2, "batgpt");
    check("bettergpt", RCPP_ARCH_GPT2, "bettergpt");
    check("bharatgpt", RCPP_ARCH_GPT2, "bharatgpt");
    check("birwkv7", RCPP_ARCH_RWKV, "birwkv7");
    check("bytegpt", RCPP_ARCH_GPT2, "bytegpt");
    check("campgpt", RCPP_ARCH_GPT2, "campgpt");
    check("circuitgpt", RCPP_ARCH_GPT2, "circuitgpt");
    check("cognitiveagent", RCPP_ARCH_GEMMA, "cognitiveagent");
    check("colmaskmoellavaqwen2", RCPP_ARCH_QWEN2, "colmaskmoellavaqwen2");
    check("convgpt", RCPP_ARCH_GPT2, "convgpt");
    check("costwisegemma", RCPP_ARCH_GEMMA, "costwisegemma");
    check("cubichierlm", RCPP_ARCH_GEMMA, "cubichierlm");
    check("dcpythia", RCPP_ARCH_GPTNEOX, "dcpythia");
    check("deepseeknano", RCPP_ARCH_DEEPSEEK, "deepseeknano");
    check("deepseekocr", RCPP_ARCH_DEEPSEEK, "deepseekocr");
    check("deepseekvlv2", RCPP_ARCH_DEEPSEEK, "deepseekvlv2");
    check("diseasegpt", RCPP_ARCH_GPT2, "diseasegpt");
    check("dyncolmaskmoellavaqwen3", RCPP_ARCH_QWEN2, "dyncolmaskmoellavaqwen3");
    check("dynhiercolmaskmoellavaqwen2", RCPP_ARCH_QWEN2, "dynhiercolmaskmoellavaqwen2");
    check("enggptmoe", RCPP_ARCH_GPT2, "enggptmoe");
    check("esm2llamainstruct", RCPP_ARCH_LLAMA, "esm2llamainstruct");
    check("evagpt", RCPP_ARCH_GPT2, "evagpt");
    check("exaone4_5_", RCPP_ARCH_LLAMA, "exaone4_5_");
    check("flex_qwen2_5_vlmoe", RCPP_ARCH_QWEN2, "flex_qwen2_5_vlmoe");
    check("gelugpt", RCPP_ARCH_GPT2, "gelugpt");
    check("gemma2moe", RCPP_ARCH_GEMMA, "gemma2moe");
    check("gemma3px", RCPP_ARCH_GEMMA, "gemma3px");
    check("gemma4e2bithybrid", RCPP_ARCH_GEMMA, "gemma4e2bithybrid");
    check("gemma4nano", RCPP_ARCH_GEMMA, "gemma4nano");
    check("glm4moeliteplusplus", RCPP_ARCH_LLAMA, "glm4moeliteplusplus");
    check("glm4v", RCPP_ARCH_LLAMA, "glm4v");
    check("goatvvv", RCPP_ARCH_GPT2, "goatvvv");
    check("gpt2vision", RCPP_ARCH_GPT2, "gpt2vision");
    check("gpt300m", RCPP_ARCH_GPT2, "gpt300m");
    check("gpt4dev", RCPP_ARCH_GPT2, "gpt4dev");
    check("gptcustom", RCPP_ARCH_GPT2, "gptcustom");
    check("gptjmoe", RCPP_ARCH_GPTJ, "gptjmoe");
    check("gptneoxjapanese", RCPP_ARCH_GPTNEOX, "gptneoxjapanese");
    check("gptossmoe", RCPP_ARCH_GPTOSS, "gptossmoe");
    check("gptossvl", RCPP_ARCH_GPTOSS, "gptossvl");
    check("gptsanjapanese", RCPP_ARCH_GPT2, "gptsanjapanese");
    check("gqagpt2", RCPP_ARCH_GPT2, "gqagpt2");
    check("granitemoeswa", RCPP_ARCH_GEMMA, "granitemoeswa");
    check("graniteswa", RCPP_ARCH_GEMMA, "graniteswa");
    check("haipailm", RCPP_ARCH_GPT2, "haipailm");
    check("hangulgemmadeobfuscator", RCPP_ARCH_GEMMA, "hangulgemmadeobfuscator");
    check("hebrewgpt", RCPP_ARCH_GPT2, "hebrewgpt");
    check("hiercolmaskmoellavaqwen2", RCPP_ARCH_QWEN2, "hiercolmaskmoellavaqwen2");
    check("huazangqwen", RCPP_ARCH_QWEN2, "huazangqwen");
    check("hybridgpt", RCPP_ARCH_GPT2, "hybridgpt");
    check("hybridmamba", RCPP_ARCH_MAMBA, "hybridmamba");
    check("hypermambalm", RCPP_ARCH_MAMBA, "hypermambalm");
    check("impphi3", RCPP_ARCH_PHI, "impphi3");
    check("latentmoellavaqwen2", RCPP_ARCH_QWEN2, "latentmoellavaqwen2");
    check("lfm2idk", RCPP_ARCH_LFM2, "lfm2idk");
    check("lfm2moecustom", RCPP_ARCH_LFM2, "lfm2moecustom");
    check("lightgpthuggingface", RCPP_ARCH_GPT2, "lightgpthuggingface");
    check("llama3custom", RCPP_ARCH_LLAMA, "llama3custom");
    check("llama3forcausallmwithearlyexit", RCPP_ARCH_LLAMA, "llama3forcausallmwithearlyexit");
    check("llamamoeupscaling", RCPP_ARCH_LLAMA, "llamamoeupscaling");
    check("llamavarlayer", RCPP_ARCH_LLAMA, "llamavarlayer");
    check("llamawithmoe", RCPP_ARCH_LLAMA, "llamawithmoe");
    check("llavamixtral", RCPP_ARCH_MISTRAL, "llavamixtral");
    check("llavapythia", RCPP_ARCH_GPTNEOX, "llavapythia");
    check("llavastablelm", RCPP_ARCH_LLAMA, "llavastablelm");
    check("mamba3causallm", RCPP_ARCH_MAMBA, "mamba3causallm");
    check("marshmellogpt", RCPP_ARCH_GPT2, "marshmellogpt");
    check("maskmoellavaqwen2", RCPP_ARCH_QWEN2, "maskmoellavaqwen2");
    check("mcgpt", RCPP_ARCH_GPT2, "mcgpt");
    check("meglm", RCPP_ARCH_LLAMA, "meglm");
    check("minicpmv", RCPP_ARCH_LLAMA, "minicpmv");
    check("minicpmv4_6", RCPP_ARCH_LLAMA, "minicpmv4_6");
    check("minideepseekv3", RCPP_ARCH_DEEPSEEK, "minideepseekv3");
    check("minideepseekv4", RCPP_ARCH_DEEPSEEK, "minideepseekv4");
    check("minigeminigemma", RCPP_ARCH_GEMMA, "minigeminigemma");
    check("miniqwen3next", RCPP_ARCH_QWEN2, "miniqwen3next");
    check("mmgptqwen", RCPP_ARCH_GPT2, "mmgptqwen");
    check("moderngptmoe", RCPP_ARCH_GPT2, "moderngptmoe");
    check("moegpt2", RCPP_ARCH_GPT2, "moegpt2");
    check("moellavamistral", RCPP_ARCH_MISTRAL, "moellavamistral");
    check("moellavaphi", RCPP_ARCH_PHI, "moellavaphi");
    check("moellavaqwen1_5", RCPP_ARCH_QWEN2, "moellavaqwen1_5");
    check("moellavastablelm", RCPP_ARCH_LLAMA, "moellavastablelm");
    check("muddpythia", RCPP_ARCH_GPTNEOX, "muddpythia");
    check("muongpt", RCPP_ARCH_GPT2, "muongpt");
    check("myphi", RCPP_ARCH_PHI, "myphi");
    check("nanochatwasmfused", RCPP_ARCH_NANOCHAT, "nanochatwasmfused");
    check("nanogptcompressed", RCPP_ARCH_GPT2, "nanogptcompressed");
    check("nemotrondenseaudex", RCPP_ARCH_NEMOTRONH, "nemotrondenseaudex");
    check("nemotronhaudex", RCPP_ARCH_NEMOTRONH, "nemotronhaudex");
    check("nemotronhpuzzle", RCPP_ARCH_NEMOTRONH, "nemotronhpuzzle");
    check("nmmaskmoellavaqwen2", RCPP_ARCH_QWEN2, "nmmaskmoellavaqwen2");
    check("nopegpthuggingface", RCPP_ARCH_GPT2, "nopegpthuggingface");
    check("nrgpt", RCPP_ARCH_GPT2, "nrgpt");
    check("olmoeuprop", RCPP_ARCH_OLMO, "olmoeuprop");
    check("optimus3", RCPP_ARCH_OPT, "optimus3");
    check("optrix", RCPP_ARCH_OPT, "optrix");
    check("phiforlogicalreasoning", RCPP_ARCH_PHI, "phiforlogicalreasoning");
    check("polyllama", RCPP_ARCH_LLAMA, "polyllama");
    check("qwen2mtp", RCPP_ARCH_QWEN2, "qwen2mtp");
    check("qwen3moeplusplus", RCPP_ARCH_QWEN2, "qwen3moeplusplus");
    check("qwen3omni", RCPP_ARCH_QWEN2, "qwen3omni");
    check("recgpt", RCPP_ARCH_GPT2, "recgpt");
    check("renneellamahfwrapper", RCPP_ARCH_LLAMA, "renneellamahfwrapper");
    check("ropegpt2", RCPP_ARCH_GPT2, "ropegpt2");
    check("rugpt3xl", RCPP_ARCH_GPT2, "rugpt3xl");
    check("rustnngpt", RCPP_ARCH_GPT2, "rustnngpt");
    check("rwkv07i", RCPP_ARCH_RWKV, "rwkv07i");
    check("rwkv07imoe", RCPP_ARCH_RWKV, "rwkv07imoe");
    check("schoolmoe", RCPP_ARCH_OLMO, "schoolmoe");
    check("semiticgpt", RCPP_ARCH_GPT2, "semiticgpt");
    check("sentinelguardedphi", RCPP_ARCH_PHI, "sentinelguardedphi");
    check("simamba", RCPP_ARCH_MAMBA, "simamba");
    check("smallllm", RCPP_ARCH_GPT2, "smallllm");
    check("smollllama", RCPP_ARCH_LLAMA, "smollllama");
    check("sologpt", RCPP_ARCH_GPT2, "sologpt");
    check("sovyn85m", RCPP_ARCH_GPT2, "sovyn85m");
    check("stepvl", RCPP_ARCH_STEP1, "stepvl");
    check("stieltjesgpt2", RCPP_ARCH_GPT2, "stieltjesgpt2");
    check("supermaskmoellavagemma", RCPP_ARCH_GEMMA, "supermaskmoellavagemma");
    check("tallavagemma", RCPP_ARCH_GEMMA, "tallavagemma");
    check("tinychartphi", RCPP_ARCH_PHI, "tinychartphi");
    check("tinyqwen3engramhc", RCPP_ARCH_QWEN2, "tinyqwen3engramhc");
    check("tinyqwen3novelty", RCPP_ARCH_QWEN2, "tinyqwen3novelty");
    check("traxl", RCPP_ARCH_GPT2, "traxl");
    check("trmgpt", RCPP_ARCH_GPT2, "trmgpt");
    check("vaultgemma", RCPP_ARCH_GEMMA, "vaultgemma");
    check("verysmollgpt", RCPP_ARCH_GPT2, "verysmollgpt");
    check("vexiongpt", RCPP_ARCH_GPT2, "vexiongpt");
    check("vopt", RCPP_ARCH_OPT, "vopt");
    check("yatfullgpt", RCPP_ARCH_GPT2, "yatfullgpt");
    check("a194logitensemble", RCPP_ARCH_A194LOGITENSEMBLE, "a194logitensemble");
    check("abir", RCPP_ARCH_ABIR, "abir");
    check("abu2head", RCPP_ARCH_ABU2HEAD, "abu2head");
    check("acerag", RCPP_ARCH_ACERAG, "acerag");
    check("acswiglu", RCPP_ARCH_ACSWIGLU, "acswiglu");
    check("adaptiveriverlm", RCPP_ARCH_ADAPTIVERIVER, "adaptiveriverlm");
    check("aethermicro", RCPP_ARCH_AETHERMICRO, "aethermicro");
    check("ailo", RCPP_ARCH_AILO, "ailo");
    check("ailoloop", RCPP_ARCH_AILOLOOP, "ailoloop");
    check("alinlight", RCPP_ARCH_ALINLIGHT, "alinlight");
    check("amadablam", RCPP_ARCH_AMADABLAM, "amadablam");
    check("ancientaiv", RCPP_ARCH_ANCIENTAIV, "ancientaiv");
    check("anubismoe", RCPP_ARCH_ANUBISMOE, "anubismoe");
    check("apriel2", RCPP_ARCH_APRIEL2, "apriel2");
    check("arar381m", RCPP_ARCH_ARAR381M, "arar381m");
    check("asclelm", RCPP_ARCH_ASCLE, "asclelm");
    check("asgtransformer", RCPP_ARCH_ASGTRANSFORMER, "asgtransformer");
    check("attnonly", RCPP_ARCH_ATTNONLY, "attnonly");
    check("autoencoder", RCPP_ARCH_AUTOENCODER, "autoencoder");
    check("autogui", RCPP_ARCH_AUTOGUI, "autogui");
    check("aveydecodermoe", RCPP_ARCH_AVEYDECODERMOE, "aveydecodermoe");
    check("axon", RCPP_ARCH_AXON, "axon");
    check("ayavision", RCPP_ARCH_AYAVISION, "ayavision");
    check("bacformerforcausalgm", RCPP_ARCH_BACFORMERGM, "bacformerforcausalgm");
    check("backboneconceptlm", RCPP_ARCH_BACKBONECONCEPT, "backboneconceptlm");
    check("baclm", RCPP_ARCH_BAC, "baclm");
    check("bailingmoelinear", RCPP_ARCH_BAILINGMOELINEAR, "bailingmoelinear");
    check("bananamind2medium", RCPP_ARCH_BANANAMIND2MEDIUM, "bananamind2medium");
    check("bananamind2micro", RCPP_ARCH_BANANAMIND2MICRO, "bananamind2micro");
    check("bananamind2mini", RCPP_ARCH_BANANAMIND2MINI, "bananamind2mini");
    check("bananamind2moe", RCPP_ARCH_BANANAMIND2MOE, "bananamind2moe");
    check("bananamind2nano", RCPP_ARCH_BANANAMIND2NANO, "bananamind2nano");
    check("bananamind2pro", RCPP_ARCH_BANANAMIND2PRO, "bananamind2pro");
    check("banglagamba", RCPP_ARCH_BANGLAGAMBA, "banglagamba");
    check("banglagsg", RCPP_ARCH_BANGLAGSG, "banglagsg");
    check("barbet", RCPP_ARCH_BARBET, "barbet");
    check("beetlemoehf", RCPP_ARCH_BEETLEMOEHF, "beetlemoehf");
    check("bharatai", RCPP_ARCH_BHARATAI, "bharatai");
    check("biatron", RCPP_ARCH_BIATRON, "biatron");
    check("bigbrainlanguage", RCPP_ARCH_BIGBRAINLANGUAGE, "bigbrainlanguage");
    check("binaryllm", RCPP_ARCH_BINARYL, "binaryllm");
    check("bitskipv1forcausallmwithearlyexit", RCPP_ARCH_BITSKIPV1WITHEARLYEXIT, "bitskipv1forcausallmwithearlyexit");
    check("bitskipv2forcausallmwithearlyexit", RCPP_ARCH_BITSKIPV2WITHEARLYEXIT, "bitskipv2forcausallmwithearlyexit");
    check("bitskipv3", RCPP_ARCH_BITSKIPV3, "bitskipv3");
    check("boramoe", RCPP_ARCH_BORAMOE, "boramoe");
    check("braille256", RCPP_ARCH_BRAILLE256, "braille256");
    check("branchycausal", RCPP_ARCH_BRANCHYCAUSAL, "branchycausal");
    check("bridgevqa", RCPP_ARCH_BRIDGEVQA, "bridgevqa");
    check("bucketmemory", RCPP_ARCH_BUCKETMEMORY, "bucketmemory");
    check("bungeo", RCPP_ARCH_BUNGEO, "bungeo");
    check("cable", RCPP_ARCH_CABLE, "cable");
    check("causallmoe", RCPP_ARCH_CAUSALLMOE, "causallmoe");
    check("celerity", RCPP_ARCH_CELERITY, "celerity");
    check("cfrd", RCPP_ARCH_CFRD, "cfrd");
    check("chameleonxllmx", RCPP_ARCH_CHAMELEONXLLMX, "chameleonxllmx");
    check("cimodel", RCPP_ARCH_CI, "cimodel");
    check("cinnabarlm", RCPP_ARCH_CINNABAR, "cinnabarlm");
    check("claritymr1", RCPP_ARCH_CLARITYMR1, "claritymr1");
    check("clinamen", RCPP_ARCH_CLINAMEN, "clinamen");
    check("cloverlm", RCPP_ARCH_CLOVER, "cloverlm");
    check("cma", RCPP_ARCH_CMA, "cma");
    check("codify", RCPP_ARCH_CODIFY, "codify");
    check("codva1", RCPP_ARCH_CODVA1, "codva1");
    check("coffeechatai", RCPP_ARCH_COFFEECHATAI, "coffeechatai");
    check("coherencemomentum", RCPP_ARCH_COHERENCEMOMENTUM, "coherencemomentum");
    check("compliantllm", RCPP_ARCH_COMPLIANTL, "compliantllm");
    check("convaicausallm", RCPP_ARCH_CONVAICAUSAL, "convaicausallm");
    check("cosmicfish", RCPP_ARCH_COSMICFISH, "cosmicfish");
    check("cpmant", RCPP_ARCH_CPMANT, "cpmant");
    check("cpmbee", RCPP_ARCH_CPMBEE, "cpmbee");
    check("cubicpipelineoptimizer", RCPP_ARCH_CUBICPIPELINEOPTIMIZER, "cubicpipelineoptimizer");
    check("cubicv11longcontext", RCPP_ARCH_CUBICV11LONGCONTEXT, "cubicv11longcontext");
    check("cubiczanmoe", RCPP_ARCH_CUBICZANMOE, "cubiczanmoe");
    check("customdecoderonlyt5", RCPP_ARCH_CUSTOMDECODERONLYT5, "customdecoderonlyt5");
    check("custommodel5", RCPP_ARCH_CUSTOM5, "custommodel5");
    check("customtagalogllm", RCPP_ARCH_CUSTOMTAGALOGL, "customtagalogllm");
    check("customtransformer", RCPP_ARCH_CUSTOMTRANSFORMER, "customtransformer");
    check("cyclicformer", RCPP_ARCH_CYCLICFORMER, "cyclicformer");
    check("d3pmsanskrit", RCPP_ARCH_D3PMSANSKRIT, "d3pmsanskrit");
    check("darkit-v1.5", RCPP_ARCH_DARKITV15, "darkit-v1.5");
    check("darkit-v2.5", RCPP_ARCH_DARKITV25, "darkit-v2.5");
    check("darwinduoorchestrator", RCPP_ARCH_DARWINDUOORCHESTRATOR, "darwinduoorchestrator");
    check("data2vectext", RCPP_ARCH_DATA2VECTEXT, "data2vectext");
    check("dcformer", RCPP_ARCH_DCFORMER, "dcformer");
    check("decoderonlytransformer", RCPP_ARCH_DECODERONLYTRANSFORMER, "decoderonlytransformer");
    check("decodon", RCPP_ARCH_DECODON, "decodon");
    check("densellm", RCPP_ARCH_DENSEL, "densellm");
    check("dfm", RCPP_ARCH_DFM, "dfm");
    check("distillix", RCPP_ARCH_DISTILLIX, "distillix");
    check("domaintransformer", RCPP_ARCH_DOMAINTRANSFORMER, "domaintransformer");
    check("dotlm", RCPP_ARCH_DOT, "dotlm");
    check("dotsocr", RCPP_ARCH_DOTSOCR, "dotsocr");
    check("dshybrid", RCPP_ARCH_DSHYBRID, "dshybrid");
    check("dwarf", RCPP_ARCH_DWARF, "dwarf");
    check("dynamicmindmoe", RCPP_ARCH_DYNAMICMINDMOE, "dynamicmindmoe");
    check("dynamicneuralnetwork", RCPP_ARCH_DYNAMICNEURALNETWORK, "dynamicneuralnetwork");
    check("echo", RCPP_ARCH_ECHO, "echo");
    check("echoes", RCPP_ARCH_ECHOES, "echoes");
    check("ecoaco", RCPP_ARCH_ECOACO, "ecoaco");
    check("elasticgpt", RCPP_ARCH_ELASTICGPT, "elasticgpt");
    check("ensemblemodel", RCPP_ARCH_ENSEMBLE, "ensemblemodel");
    check("erklinear", RCPP_ARCH_ERKLINEAR, "erklinear");
    check("evafrillmo", RCPP_ARCH_EVAFRILLMO, "evafrillmo");
    check("evemoe", RCPP_ARCH_EVEMOE, "evemoe");
    check("evo1", RCPP_ARCH_EVO1, "evo1");
    check("fastplus", RCPP_ARCH_FASTPLUS, "fastplus");
    check("fastplus125m", RCPP_ARCH_FASTPLUS125M, "fastplus125m");
    check("fastplus40m", RCPP_ARCH_FASTPLUS40M, "fastplus40m");
    check("fasty", RCPP_ARCH_FASTY, "fasty");
    check("fela", RCPP_ARCH_FELA, "fela");
    check("fern3b", RCPP_ARCH_FERN3B, "fern3b");
    check("fieldshub", RCPP_ARCH_FIELDSHUB, "fieldshub");
    check("fiphi-neuralark-3.9-ultra", RCPP_ARCH_FIPHINEURALARK39ULTRA, "fiphi-neuralark-3.9-ultra");
    check("fixedenhancedhybridtransformer", RCPP_ARCH_FIXEDENHANCEDHYBRIDTRANS, "fixedenhancedhybridtransformer");
    check("flexrank", RCPP_ARCH_FLEXRANK, "flexrank");
    check("fontainelm", RCPP_ARCH_FONTAINE, "fontainelm");
    check("frawdllm", RCPP_ARCH_FRAWDL, "frawdllm");
    check("frenchllm", RCPP_ARCH_FRENCHL, "frenchllm");
    check("fsgpt", RCPP_ARCH_FSGPT, "fsgpt");
    check("fsgptmoe", RCPP_ARCH_FSGPTMOE, "fsgptmoe");
    check("fuse3", RCPP_ARCH_FUSE3, "fuse3");
    check("fuse3v2", RCPP_ARCH_FUSE3V2, "fuse3v2");
    check("futuregq47m", RCPP_ARCH_FUTUREGQ47M, "futuregq47m");
    check("futuregq47q", RCPP_ARCH_FUTUREGQ47Q, "futuregq47q");
    check("fuxitranyu", RCPP_ARCH_FUXITRANYU, "fuxitranyu");
    check("fwkvlanguage", RCPP_ARCH_FWKVLANGUAGE, "fwkvlanguage");
    check("g0nano", RCPP_ARCH_G0NANO, "g0nano");
    check("gad2foragenticmodeling", RCPP_ARCH_GAD2FORAGENTICING, "gad2foragenticmodeling");
    check("gadforagenticmodeling", RCPP_ARCH_GADFORAGENTICING, "gadforagenticmodeling");
    check("galahad", RCPP_ARCH_GALAHAD, "galahad");
    check("gateddeltaproduct", RCPP_ARCH_GATEDDELTAPRODUCT, "gateddeltaproduct");
    check("gazelle", RCPP_ARCH_GAZELLE, "gazelle");
    check("gembytiny", RCPP_ARCH_GEMBYTINY, "gembytiny");
    check("geov", RCPP_ARCH_GEOV, "geov");
    check("giftofgab", RCPP_ARCH_GIFTOFGAB, "giftofgab");
    check("glublm", RCPP_ARCH_GLUB, "glublm");
    check("godqueeniv", RCPP_ARCH_GODQUEENIV, "godqueeniv");
    check("gravitymoe", RCPP_ARCH_GRAVITYMOE, "gravitymoe");
    check("grok2", RCPP_ARCH_GROK2, "grok2");
    check("groundedbliplm", RCPP_ARCH_GROUNDEDBLIP, "groundedbliplm");
    check("guppylm", RCPP_ARCH_GUPPY, "guppylm");
    check("h2ovlchat", RCPP_ARCH_H2OVLCHAT, "h2ovlchat");
    check("haipai", RCPP_ARCH_HAIPAI, "haipai");
    check("haltcot", RCPP_ARCH_HALTCOT, "haltcot");
    check("hanforge", RCPP_ARCH_HANFORGE, "hanforge");
    check("hcxvision", RCPP_ARCH_HCXVISION, "hcxvision");
    check("hcxvisionv2", RCPP_ARCH_HCXVISIONV2, "hcxvisionv2");
    check("helloagent", RCPP_ARCH_HELLOAGENT, "helloagent");
    check("henlaconfed", RCPP_ARCH_HENLACONFED, "henlaconfed");
    check("hfbyteetm", RCPP_ARCH_HFBYTEETM, "hfbyteetm");
    check("hfopenmoe", RCPP_ARCH_HFOPENMOE, "hfopenmoe");
    check("hindicausallm", RCPP_ARCH_HINDICAUSAL, "hindicausallm");
    check("hlm5", RCPP_ARCH_HLM5, "hlm5");
    check("hrm", RCPP_ARCH_HRM, "hrm");
    check("hrmcosmicfish", RCPP_ARCH_HRMCOSMICFISH, "hrmcosmicfish");
    check("hrmtextmoe", RCPP_ARCH_HRMTEXTMOE, "hrmtextmoe");
    check("htdn", RCPP_ARCH_HTDN, "htdn");
    check("hybridecho", RCPP_ARCH_HYBRIDECHO, "hybridecho");
    check("hybridfourierlm", RCPP_ARCH_HYBRIDFOURIER, "hybridfourierlm");
    check("hybridgateddeltanet", RCPP_ARCH_HYBRIDGATEDDELTANET, "hybridgateddeltanet");
    check("hybridmormoe", RCPP_ARCH_HYBRIDMORMOE, "hybridmormoe");
    check("hybridtiny", RCPP_ARCH_HYBRIDTINY, "hybridtiny");
    check("hybridtransformerv2", RCPP_ARCH_HYBRIDTRANSFORMERV2, "hybridtransformerv2");
    check("hybriko", RCPP_ARCH_HYBRIKO, "hybriko");
    check("i3hybridchat", RCPP_ARCH_I3HYBRIDCHAT, "i3hybridchat");
    check("infimmhd", RCPP_ARCH_INFIMMHD, "infimmhd");
    check("infimmvicuna", RCPP_ARCH_INFIMMVICUNA, "infimmvicuna");
    check("infimmzephyr", RCPP_ARCH_INFIMMZEPHYR, "infimmzephyr");
    check("inkling", RCPP_ARCH_INKLING, "inkling");
    check("inversionfromhiddenstates", RCPP_ARCH_INVERSIONFROMHIDDENSTATE, "inversionfromhiddenstates");
    check("ions1", RCPP_ARCH_IONS1, "ions1");
    check("isllmai50m", RCPP_ARCH_ISLLMAI50M, "isllmai50m");
    check("ivmecoderv1", RCPP_ARCH_IVMECODERV1, "ivmecoderv1");
    check("ivmeconversates", RCPP_ARCH_IVMECONVERSATES, "ivmeconversates");
    check("ivmeconversatesv2instruct", RCPP_ARCH_IVMECONVERSATESV2INSTRUC, "ivmeconversatesv2instruct");
    check("ivmexl", RCPP_ARCH_IVMEXL, "ivmexl");
    check("jeeney", RCPP_ARCH_JEENEY, "jeeney");
    check("jeeves", RCPP_ARCH_JEEVES, "jeeves");
    check("judgexl", RCPP_ARCH_JUDGEXL, "judgexl");
    check("kateai", RCPP_ARCH_KATEAI, "kateai");
    check("keystonefuse", RCPP_ARCH_KEYSTONEFUSE, "keystonefuse");
    check("kfm", RCPP_ARCH_KFM, "kfm");
    check("klearmoe", RCPP_ARCH_KLEARMOE, "klearmoe");
    check("knkvf", RCPP_ARCH_KNKVF, "knkvf");
    check("koprialm", RCPP_ARCH_KOPRIA, "koprialm");
    check("kormomoe", RCPP_ARCH_KORMOMOE, "kormomoe");
    check("kosmos2_5text", RCPP_ARCH_KOSMOS25TEXT, "kosmos2_5text");
    check("ksbyte", RCPP_ARCH_KSBYTE, "ksbyte");
    check("kvlatent", RCPP_ARCH_KVLATENT, "kvlatent");
    check("laminarnet", RCPP_ARCH_LAMINARNET, "laminarnet");
    check("lanceai", RCPP_ARCH_LANCEAI, "lanceai");
    check("laneformer", RCPP_ARCH_LANEFORMER, "laneformer");
    check("latentrecurrentdepth", RCPP_ARCH_LATENTRECURRENTDEPTH, "latentrecurrentdepth");
    check("ledgernet", RCPP_ARCH_LEDGERNET, "ledgernet");
    check("ligergla", RCPP_ARCH_LIGERGLA, "ligergla");
    check("lightbrainhybrid", RCPP_ARCH_LIGHTBRAINHYBRID, "lightbrainhybrid");
    check("llavamonet", RCPP_ARCH_LLAVAMONET, "llavamonet");
    check("llavavistral", RCPP_ARCH_LLAVAVISTRAL, "llavavistral");
    check("lltransformer", RCPP_ARCH_LLTRANSFORMER, "lltransformer");
    check("loaflm", RCPP_ARCH_LOAF, "loaflm");
    check("localllm", RCPP_ARCH_LOCALL, "localllm");
    check("loleve", RCPP_ARCH_LOLEVE, "loleve");
    check("longcat", RCPP_ARCH_LONGCAT, "longcat");
    check("longcatflashomni", RCPP_ARCH_LONGCATFLASHOMNI, "longcatflashomni");
    check("longcatnext", RCPP_ARCH_LONGCATNEXT, "longcatnext");
    check("loomformer", RCPP_ARCH_LOOMFORMER, "loomformer");
    check("lsmoe", RCPP_ARCH_LSMOE, "lsmoe");
    check("lswt", RCPP_ARCH_LSWT, "lswt");
    check("lumees", RCPP_ARCH_LUMEES, "lumees");
    check("lumen", RCPP_ARCH_LUMEN, "lumen");
    check("lumenspark", RCPP_ARCH_LUMENSPARK, "lumenspark");
    check("maccy", RCPP_ARCH_MACCY, "maccy");
    check("magnetar", RCPP_ARCH_MAGNETAR, "magnetar");
    check("markupdm", RCPP_ARCH_MARKUPDM, "markupdm");
    check("mathbananamind", RCPP_ARCH_MATHBANANAMIND, "mathbananamind");
    check("matilda", RCPP_ARCH_MATILDA, "matilda");
    check("matriochka", RCPP_ARCH_MATRIOCHKA, "matriochka");
    check("mcqhf", RCPP_ARCH_MCQHF, "mcqhf");
    check("mdlm", RCPP_ARCH_MD, "mdlm");
    check("mdlmbpev4", RCPP_ARCH_MDLMBPEV4, "mdlmbpev4");
    check("medhemo", RCPP_ARCH_MEDHEMO, "medhemo");
    check("medhemoearcp", RCPP_ARCH_MEDHEMOEARCP, "medhemoearcp");
    check("megatron", RCPP_ARCH_MEGATRON, "megatron");
    check("megrezmoe", RCPP_ARCH_MEGREZMOE, "megrezmoe");
    check("metallm", RCPP_ARCH_METAL, "metallm");
    check("metismor", RCPP_ARCH_METISMOR, "metismor");
    check("microbanana", RCPP_ARCH_MICROBANANA, "microbanana");
    check("microstorybananamind", RCPP_ARCH_MICROSTORYBANANAMIND, "microstorybananamind");
    check("mingru", RCPP_ARCH_MINGRU, "mingru");
    check("mingrulm", RCPP_ARCH_MINGRU_MING, "mingrulm");
    check("miniart", RCPP_ARCH_MINIART, "miniart");
    check("minienedina", RCPP_ARCH_MINIENEDINA, "minienedina");
    check("minigeminimixtral", RCPP_ARCH_MINIGEMINIMIXTRAL, "minigeminimixtral");
    check("minitransformer", RCPP_ARCH_MINITRANSFORMER, "minitransformer");
    check("minspark", RCPP_ARCH_MINSPARK, "minspark");
    check("miridih_llava", RCPP_ARCH_MIRIDIHLLAVA, "miridih_llava");
    check("mixtral 8x7b", RCPP_ARCH_MIXTRAL8X7B, "mixtral 8x7b");
    check("mlpspeculatorpretrained", RCPP_ARCH_MLPSPECULATORPRETRAINED, "mlpspeculatorpretrained");
    check("mmmadnessllmmodel", RCPP_ARCH_MMMADNESSLLM, "mmmadnessllmmodel");
    check("moametriclm", RCPP_ARCH_MOAMETRIC, "moametriclm");
    check("mobilintcohere2", RCPP_ARCH_MOBILINTCOHERE2, "mobilintcohere2");
    check("mochiva", RCPP_ARCH_MOCHIVA, "mochiva");
    check("moduleformer", RCPP_ARCH_MODULEFORMER, "moduleformer");
    check("moe", RCPP_ARCH_MOE, "moe");
    check("moetransformer", RCPP_ARCH_MOETRANSFORMER, "moetransformer");
    check("moiraicausallm", RCPP_ARCH_MOIRAICAUSAL, "moiraicausallm");
    check("molexar", RCPP_ARCH_MOLEXAR, "molexar");
    check("monad1", RCPP_ARCH_MONAD1, "monad1");
    check("mothercore", RCPP_ARCH_MOTHERCORE, "mothercore");
    check("muddformer", RCPP_ARCH_MUDDFORMER, "muddformer");
    check("multimodalsuper", RCPP_ARCH_MULTIMODALSUPER, "multimodalsuper");
    check("multiscreen", RCPP_ARCH_MULTISCREEN, "multiscreen");
    check("muxx11", RCPP_ARCH_MUXX11, "muxx11");
    check("mycoach", RCPP_ARCH_MYCOACH, "mycoach");
    check("mygrok", RCPP_ARCH_MYGROK, "mygrok");
    check("nablavl", RCPP_ARCH_NABLAVL, "nablavl");
    check("nafie", RCPP_ARCH_NAFIE, "nafie");
    check("nanochrono", RCPP_ARCH_NANOCHRONO, "nanochrono");
    check("nanomoe", RCPP_ARCH_NANOMOE, "nanomoe");
    check("nanos1_1lite", RCPP_ARCH_NANOS11LITE, "nanos1_1lite");
    check("nanothink", RCPP_ARCH_NANOTHINK, "nanothink");
    check("nanotransformer", RCPP_ARCH_NANOTRANSFORMER, "nanotransformer");
    check("nanowhaledime", RCPP_ARCH_NANOWHALEDIME, "nanowhaledime");
    check("narctiny", RCPP_ARCH_NARCTINY, "narctiny");
    check("naturecodeocean", RCPP_ARCH_NATURECODEOCEAN, "naturecodeocean");
    check("ndlmoe", RCPP_ARCH_NDLMOE, "ndlmoe");
    check("nee", RCPP_ARCH_NEE, "nee");
    check("needconversational", RCPP_ARCH_NEEDCONVERSATIONAL, "needconversational");
    check("nekomindmoe", RCPP_ARCH_NEKOMINDMOE, "nekomindmoe");
    check("nepaledgelm", RCPP_ARCH_NEPALEDGE, "nepaledgelm");
    check("neuronlm", RCPP_ARCH_NEURON, "neuronlm");
    check("neuronspark", RCPP_ARCH_NEURONSPARK, "neuronspark");
    check("nexara", RCPP_ARCH_NEXARA, "nexara");
    check("ngen3", RCPP_ARCH_NGEN3, "ngen3");
    check("ngen3forcasuallm", RCPP_ARCH_NGEN3_NGEN, "ngen3forcasuallm");
    check("ngen4", RCPP_ARCH_NGEN4, "ngen4");
    check("ngen4ow10t", RCPP_ARCH_NGEN4OW10T, "ngen4ow10t");
    check("nilex", RCPP_ARCH_NILEX, "nilex");
    check("noeum", RCPP_ARCH_NOEUM, "noeum");
    check("notokengen", RCPP_ARCH_NOTOKENGEN, "notokengen");
    check("ntv3generative", RCPP_ARCH_NTV3GENERATIVE, "ntv3generative");
    check("nushy5", RCPP_ARCH_NUSHY5, "nushy5");
    check("obilanguage", RCPP_ARCH_OBILANGUAGE, "obilanguage");
    check("obsidianmultiscreen", RCPP_ARCH_OBSIDIANMULTISCREEN, "obsidianmultiscreen");
    check("odinnext", RCPP_ARCH_ODINNEXT, "odinnext");
    check("olm3nano", RCPP_ARCH_OLM3NANO, "olm3nano");
    check("openmythos", RCPP_ARCH_OPENMYTHOS, "openmythos");
    check("openthaiwilai", RCPP_ARCH_OPENTHAIWILAI, "openthaiwilai");
    check("openvlaforactionprediction", RCPP_ARCH_OPENVLAFORACTIONPREDICTI, "openvlaforactionprediction");
    check("orionmoecausallm", RCPP_ARCH_ORIONMOECAUSAL, "orionmoecausallm");
    check("os24", RCPP_ARCH_OS24, "os24");
    check("otterlm", RCPP_ARCH_OTTER, "otterlm");
    check("outliermoe", RCPP_ARCH_OUTLIERMOE, "outliermoe");
    check("packedllm", RCPP_ARCH_PACKEDL, "packedllm");
    check("pagnolxl", RCPP_ARCH_PAGNOLXL, "pagnolxl");
    check("paintermodel", RCPP_ARCH_PAINTER, "paintermodel");
    check("panolm", RCPP_ARCH_PANO, "panolm");
    check("param1moe", RCPP_ARCH_PARAM1MOE, "param1moe");
    check("param2moe", RCPP_ARCH_PARAM2MOE, "param2moe");
    check("paramtatvatransformer", RCPP_ARCH_PARAMTATVATRANSFORMER, "paramtatvatransformer");
    check("parchment", RCPP_ARCH_PARCHMENT, "parchment");
    check("persimmon", RCPP_ARCH_PERSIMMON, "persimmon");
    check("pinanolm100m", RCPP_ARCH_PINANOLM100M, "pinanolm100m");
    check("pinanolm20m", RCPP_ARCH_PINANOLM20M, "pinanolm20m");
    check("pinanolm50m", RCPP_ARCH_PINANOLM50M, "pinanolm50m");
    check("pinkelephant", RCPP_ARCH_PINKELEPHANT, "pinkelephant");
    check("plapt", RCPP_ARCH_PLAPT, "plapt");
    check("plbart", RCPP_ARCH_PLBART, "plbart");
    check("pletinylm", RCPP_ARCH_PLETINY, "pletinylm");
    check("pm_minifinllm_", RCPP_ARCH_PMMINIFINL, "pm_minifinllm_");
    check("porthormoe", RCPP_ARCH_PORTHORMOE, "porthormoe");
    check("prajnastudentmultilayer", RCPP_ARCH_PRAJNASTUDENTMULTILAYER, "prajnastudentmultilayer");
    check("pratchya", RCPP_ARCH_PRATCHYA, "pratchya");
    check("prismcharmlp", RCPP_ARCH_PRISMCHARMLP, "prismcharmlp");
    check("privatellm", RCPP_ARCH_PRIVATEL, "privatellm");
    check("pzdrk-reasoning", RCPP_ARCH_PZDRKREASONING, "pzdrk-reasoning");
    check("qmoe", RCPP_ARCH_QMOE, "qmoe");
    check("qofficesuiteruntime", RCPP_ARCH_QOFFICESUITERUNTIME, "qofficesuiteruntime");
    check("qovaryx", RCPP_ARCH_QOVARYX, "qovaryx");
    check("quadorbit", RCPP_ARCH_QUADORBIT, "quadorbit");
    check("ramo", RCPP_ARCH_RAMO, "ramo");
    check("ravenguard", RCPP_ARCH_RAVENGUARD, "ravenguard");
    check("realtransformer", RCPP_ARCH_REALTRANSFORMER, "realtransformer");
    check("recombinationtransformer", RCPP_ARCH_RECOMBINATIONTRANSFORMER, "recombinationtransformer");
    check("recursivecompressorlm", RCPP_ARCH_RECURSIVECOMPRESSOR, "recursivecompressorlm");
    check("recursivelanguage", RCPP_ARCH_RECURSIVELANGUAGE, "recursivelanguage");
    check("regressionisattention", RCPP_ARCH_REGRESSIONISATTENTION, "regressionisattention");
    check("ritamodel", RCPP_ARCH_RITA, "ritamodel");
    check("rubirlm", RCPP_ARCH_RUBIR, "rubirlm");
    check("saffu", RCPP_ARCH_SAFFU, "saffu");
    check("sasequintillionasi", RCPP_ARCH_SASEQUINTILLIONASI, "sasequintillionasi");
    check("sdarmoe", RCPP_ARCH_SDARMOE, "sdarmoe");
    check("sentinelbrain", RCPP_ARCH_SENTINELBRAIN, "sentinelbrain");
    check("seqax", RCPP_ARCH_SEQAX, "seqax");
    check("seqcond", RCPP_ARCH_SEQCOND, "seqcond");
    check("sermental", RCPP_ARCH_SERMENTAL, "sermental");
    check("sewyv2", RCPP_ARCH_SEWYV2, "sewyv2");
    check("shivikm1", RCPP_ARCH_SHIVIKM1, "shivikm1");
    check("shivikm2", RCPP_ARCH_SHIVIKM2, "shivikm2");
    check("shivikm4", RCPP_ARCH_SHIVIKM4, "shivikm4");
    check("shrinkmodel", RCPP_ARCH_SHRINK, "shrinkmodel");
    check("siger", RCPP_ARCH_SIGER, "siger");
    check("simplestories", RCPP_ARCH_SIMPLESTORIES, "simplestories");
    check("simplestories4m", RCPP_ARCH_SIMPLESTORIES4M, "simplestories4m");
    check("sixpertmoe", RCPP_ARCH_SIXPERTMOE, "sixpertmoe");
    check("slimmoe", RCPP_ARCH_SLIMMOE, "slimmoe");
    check("slmoe", RCPP_ARCH_SLMOE, "slmoe");
    check("smalllanguage", RCPP_ARCH_SMALLLANGUAGE, "smalllanguage");
    check("smartcodermoe", RCPP_ARCH_SMARTCODERMOE, "smartcodermoe");
    check("smdm", RCPP_ARCH_SMDM, "smdm");
    check("smmodel", RCPP_ARCH_SM, "smmodel");
    check("smtmodel", RCPP_ARCH_SMT, "smtmodel");
    check("sofanor", RCPP_ARCH_SOFANOR, "sofanor");
    check("solollm", RCPP_ARCH_SOLOL, "solollm");
    check("sonamath", RCPP_ARCH_SONAMATH, "sonamath");
    check("soraforslm", RCPP_ARCH_SORAFORS, "soraforslm");
    check("sovythos", RCPP_ARCH_SOVYTHOS, "sovythos");
    check("sphericalkanbytelm", RCPP_ARCH_SPHERICALKANBYTE, "sphericalkanbytelm");
    check("srcprober", RCPP_ARCH_SRCPROBER, "srcprober");
    check("statehead", RCPP_ARCH_STATEHEAD, "statehead");
    check("steerling", RCPP_ARCH_STEERLING, "steerling");
    check("stellarai", RCPP_ARCH_STELLARAI, "stellarai");
    check("stochasticfrequencyfilter", RCPP_ARCH_STOCHASTICFREQUENCYFILTE, "stochasticfrequencyfilter");
    check("suprabrain", RCPP_ARCH_SUPRABRAIN, "suprabrain");
    check("swarmmoe", RCPP_ARCH_SWARMMOE, "swarmmoe");
    check("sweta", RCPP_ARCH_SWETA, "sweta");
    check("sykocausallm", RCPP_ARCH_SYKOCAUSAL, "sykocausallm");
    check("tahqiqgenesis", RCPP_ARCH_TAHQIQGENESIS, "tahqiqgenesis");
    check("tamazight", RCPP_ARCH_TAMAZIGHT, "tamazight");
    check("tamelm", RCPP_ARCH_TAME, "tamelm");
    check("tamiltinystories", RCPP_ARCH_TAMILTINYSTORIES, "tamiltinystories");
    check("taonetminit2", RCPP_ARCH_TAONETMINIT2, "taonetminit2");
    check("tcmoe", RCPP_ARCH_TCMOE, "tcmoe");
    check("thinkerlm", RCPP_ARCH_THINKER, "thinkerlm");
    check("tiny", RCPP_ARCH_TINY, "tiny");
    check("tinybuddy", RCPP_ARCH_TINYBUDDY, "tinybuddy");
    check("tinylm", RCPP_ARCH_TINY_TINY, "tinylm");
    check("tinymind", RCPP_ARCH_TINYMIND, "tinymind");
    check("tinypellm", RCPP_ARCH_TINYPEL, "tinypellm");
    check("tinyv4", RCPP_ARCH_TINYV4, "tinyv4");
    check("tinyway", RCPP_ARCH_TINYWAY, "tinyway");
    check("tnl1-385m-10b-token_no-act", RCPP_ARCH_TNL1385M10BTOKENNOACT, "tnl1-385m-10b-token_no-act");
    check("tokenformer", RCPP_ARCH_TOKENFORMER, "tokenformer");
    check("tokilm", RCPP_ARCH_TOKI, "tokilm");
    check("toyllm", RCPP_ARCH_TOYL, "toyllm");
    check("transcoremqwen", RCPP_ARCH_TRANSCOREMQWEN, "transcoremqwen");
    check("transformerchatbot", RCPP_ARCH_TRANSFORMERCHATBOT, "transformerchatbot");
    check("transformermodel", RCPP_ARCH_TRANSFORMER, "transformermodel");
    check("transformerwithpruning", RCPP_ARCH_TRANSFORMERWITHPRUNING, "transformerwithpruning");
    check("trmtextism", RCPP_ARCH_TRMTEXTISM, "trmtextism");
    check("trocr", RCPP_ARCH_TROCR, "trocr");
    check("trtcv4", RCPP_ARCH_TRTCV4, "trtcv4");
    check("tttpilotmac", RCPP_ARCH_TTTPILOTMAC, "tttpilotmac");
    check("turinglm", RCPP_ARCH_TURING, "turinglm");
    check("twinkelllm", RCPP_ARCH_TWINKELL, "twinkelllm");
    check("tynerox", RCPP_ARCH_TYNEROX, "tynerox");
    check("ullava", RCPP_ARCH_ULLAVA, "ullava");
    check("ullavacore", RCPP_ARCH_ULLAVACORE, "ullavacore");
    check("unifiedlm", RCPP_ARCH_UNIFIED, "unifiedlm");
    check("urchinparallel", RCPP_ARCH_URCHINPARALLEL, "urchinparallel");
    check("vanfast", RCPP_ARCH_VANFAST, "vanfast");
    check("vegalm", RCPP_ARCH_VEGA, "vegalm");
    check("vegav1", RCPP_ARCH_VEGAV1, "vegav1");
    check("veramoelite", RCPP_ARCH_VERAMOELITE, "veramoelite");
    check("verantyx", RCPP_ARCH_VERANTYX, "verantyx");
    check("vgt_8l_engine", RCPP_ARCH_VGT8LENGINE, "vgt_8l_engine");
    check("vilaforcasuallm", RCPP_ARCH_VILA, "vilaforcasuallm");
    check("vlite3", RCPP_ARCH_VLITE3, "vlite3");
    check("vlite3_5", RCPP_ARCH_VLITE35, "vlite3_5");
    check("vlite7", RCPP_ARCH_VLITE7, "vlite7");
    check("vlite7mini20m", RCPP_ARCH_VLITE7MINI20M, "vlite7mini20m");
    check("vrinda", RCPP_ARCH_VRINDA, "vrinda");
    check("vritya", RCPP_ARCH_VRITYA, "vritya");
    check("vsb", RCPP_ARCH_VSB, "vsb");
    check("wasminterpretertransformer", RCPP_ARCH_WASMINTERPRETERTRANSFORM, "wasminterpretertransformer");
    check("wbot_1_5", RCPP_ARCH_WBOT15, "wbot_1_5");
    check("welmia", RCPP_ARCH_WELMIA, "welmia");
    check("wildnerve_tlm01", RCPP_ARCH_WILDNERVETLM01, "wildnerve_tlm01");
    check("wiola", RCPP_ARCH_WIOLA, "wiola");
    check("wordlatenttransformer", RCPP_ARCH_WORDLATENTTRANSFORMER, "wordlatenttransformer");
    check("wyrmling", RCPP_ARCH_WYRMLING, "wyrmling");
    check("xerobioai", RCPP_ARCH_XEROBIOAI, "xerobioai");
    check("xlstm", RCPP_ARCH_XLSTM, "xlstm");
    check("xomdich", RCPP_ARCH_XOMDICH, "xomdich");
    check("yazh", RCPP_ARCH_YAZH, "yazh");
    check("yforcausallm1_1", RCPP_ARCH_Y11, "yforcausallm1_1");
    check("yforcausallm2", RCPP_ARCH_Y2, "yforcausallm2");
    check("yforcausallm3", RCPP_ARCH_Y3, "yforcausallm3");
    check("yforcausallm31", RCPP_ARCH_Y31, "yforcausallm31");
    check("zetagrid25b", RCPP_ARCH_ZETAGRID25B, "zetagrid25b");
    check("zipformer", RCPP_ARCH_ZIPFORMER, "zipformer");
    check("zorixnano", RCPP_ARCH_ZORIXNANO, "zorixnano");
    check("zzjrabbit2", RCPP_ARCH_ZZJRABBIT2, "zzjrabbit2");
    check("zzjrabbit22", RCPP_ARCH_ZZJRABBIT22, "zzjrabbit22");
    check("zzjrabbit3", RCPP_ARCH_ZZJRABBIT3, "zzjrabbit3");
    check("zzjrabbitmodel", RCPP_ARCH_ZZJRABBIT, "zzjrabbitmodel");

    // ── 2026-08-16 MONSTER ticket closures (#1649-#1687) — arch mappings landed with the
    //    engine bring-up; these lock in the registry mapping each ticket required.
    check("granitemoehybrid", RCPP_ARCH_GRANITEMOEHYBRID, "granitemoehybrid (#1649)");
    check("qwen3next", RCPP_ARCH_QWEN3NEXT, "qwen3next (#1650)");
    check("minimaxm2", RCPP_ARCH_MINIMAXM2, "minimaxm2 (#1651)");
    check("lfm2moe", RCPP_ARCH_LFM2MOE, "lfm2moe (#1655)");
    check("cohere2", RCPP_ARCH_COHERE2, "cohere2 (#1656)");
    check("falconh1", RCPP_ARCH_FALCONH1, "falconh1 (#1657)");
    check("dflashdraft", RCPP_ARCH_QWEN3, "dflashdraft (#1659) — DFlashDraftModel model_type qwen3");
    check("rwkv", RCPP_ARCH_RWKV, "rwkv (#1660)");
    check("dynamicalibi", RCPP_ARCH_DYNAMICALIBI, "dynamicalibi (#1663)");
    check("opensci", RCPP_ARCH_LLAMA, "opensci (#1664)");
    check("transformer", RCPP_ARCH_GPT2, "transformer (#1665) — gpt2 profile (codeparrot-small)");
    check("nanochat", RCPP_ARCH_NANOCHAT, "nanochat (#1668)");
    check("afmoe", RCPP_ARCH_AFMOE, "afmoe (#1669)");
    check("lisa", RCPP_ARCH_GPT2, "lisa (#1670) — dialogpt-based gpt2 profile");
    check("gpt", RCPP_ARCH_GPT2, "gpt (#1673) — GptForCausalLM gpt2 profile");
    check("chess", RCPP_ARCH_GPT2, "chess (#1680) — ChessForCausalLM gpt2 layout");
    check("ernie4_5_moe", RCPP_ARCH_ERNIE45MOE, "ernie4_5_moe (#1682)");
    check("llada", RCPP_ARCH_LLAMA, "llada (#1685) — llama profile");
    check("slm", RCPP_ARCH_LLAMA, "slm (#1686) — sathishphdai SLM family");
    check("bailingmoe", RCPP_ARCH_LLAMA, "bailingmoe (#1683) — llama-layout MoE");
    check("sarvammoe", RCPP_ARCH_SARVAM, "sarvammoe (#1684)");
    check("mellum", RCPP_ARCH_MELLUM, "mellum (#1687)");
    check("raven", RCPP_ARCH_RAVEN, "raven (#1687)");
    check("talkie", RCPP_ARCH_TALKIE, "talkie (#1687)");
    check("sdar", RCPP_ARCH_GPT2, "sdar (#1687) — gpt2 profile");
    check("caca", RCPP_ARCH_LLAMA, "caca (#1687) — llama profile");
    check("kimik25", RCPP_ARCH_DEEPSEEK, "kimik25 (#1687) — deepseek-v3 layout");
    check("detikzify", RCPP_ARCH_LLAMA, "detikzify (#1687) — llama text decoder");
    check("iquestcoder", RCPP_ARCH_LLAMA, "iquestcoder (#1687) — llama profile");
    check("helix", RCPP_ARCH_GPT2, "helix (#1687) — gpt2 profile");
    std::printf("ARCH MAPPING: all %d checks passed\n", total);
    return 0;
}
